import { ElementRef, OnDestroy, DoCheck, Renderer, KeyValueDiffers, SimpleChanges, OnChanges } from '@angular/core';
import { NgStyle } from '@angular/common';
import { BaseFxDirectiveAdapter } from './base-adapter';
import { MediaMonitor } from '../../media-query/media-monitor';
import { DomSanitizer } from '@angular/platform-browser';
import { NgStyleType } from '../../utils/style-transforms';
export declare const _StyleDirectiveBaseClass: typeof NgStyle;
export declare class StyleDirective extends _StyleDirectiveBaseClass implements DoCheck, OnChanges, OnDestroy {
    private monitor;
    protected _sanitizer: DomSanitizer;
    styleBase: NgStyleType;
    ngStyleXs: NgStyleType;
    ngStyleSm: NgStyleType;
    ngStyleMd: NgStyleType;
    ngStyleLg: NgStyleType;
    ngStyleXl: NgStyleType;
    ngStyleLtSm: NgStyleType;
    ngStyleLtMd: NgStyleType;
    ngStyleLtLg: NgStyleType;
    ngStyleLtXl: NgStyleType;
    ngStyleGtXs: NgStyleType;
    ngStyleGtSm: NgStyleType;
    ngStyleGtMd: NgStyleType;
    ngStyleGtLg: NgStyleType;
    styleXs: NgStyleType;
    styleSm: NgStyleType;
    styleMd: NgStyleType;
    styleLg: NgStyleType;
    styleXl: NgStyleType;
    styleLtSm: NgStyleType;
    styleLtMd: NgStyleType;
    styleLtLg: NgStyleType;
    styleLtXl: NgStyleType;
    styleGtXs: NgStyleType;
    styleGtSm: NgStyleType;
    styleGtMd: NgStyleType;
    styleGtLg: NgStyleType;
    constructor(monitor: MediaMonitor, _sanitizer: DomSanitizer, _differs: KeyValueDiffers, _ngEl: ElementRef, _renderer: Renderer);
    ngOnChanges(changes: SimpleChanges): void;
    ngDoCheck(): void;
    ngOnDestroy(): void;
    protected _configureMQListener(): void;
    protected _updateStyle(value?: NgStyleType): void;
    protected _buildAdapter(monitor: MediaMonitor, _ngEl: ElementRef, _renderer: Renderer): void;
    protected _buildCacheInterceptor(): void;
    protected _buildStyleMap(styles: NgStyleType): NgStyleType;
    protected _base: BaseFxDirectiveAdapter;
}
