import './tasks/changelog';
import './tasks/ci';
import './tasks/clean';
import './tasks/components';
import './tasks/default';
import './tasks/lint';
import './tasks/release';
import './tasks/clang-format.js';
import './tasks/unit-test';
