name: Lock issues that are closed and inactive

on:
  schedule:
    # Run everday at 12:00
    - cron: '0 12 * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@0fc6f4d839e93312ed0dd9a2be88d4c11e947a0b
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
          locks-per-execution: 100
