name: Lock issues that are closed and inactive

on:
  schedule:
    # Run at the top of every hour
    - cron: '0 * * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@7f7ef07
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
          locks-per-execution: 100
